### ISSUE TITLE
iTwin table with combo box leading to unhandled scroll behavior

### ISSUE THREAD

**Issue by vsnandanwar** [iTwin/iTwinUI#884] opened 2022-12-06 11:24 UTC
#### Describe the bug (actual behavior)
iTwin Table row with Combobox leading to unhandled scroll. The table is scrolling up and down continuously without scrolling using a mouse or keyboard. 

#### Expected behavior
It should not distract the UI. Scroll behavior should be smooth.
![20221206_164517](https://user-images.githubusercontent.com/108334178/205898970-a18142d5-588e-4f4a-b0ac-81464e5966ae.gif)

**Comment by vsnandanwar** [comment] 2023-01-10 10:42
Hi @mayank99 @rohan-kadkol @gretanausedaite @adamhock ,

Have you started working on this issue or any progress on this? Will you please give me the update on the status?

**Comment by FlyersPh9** [comment] 2023-01-10 16:05
Hi @vsnandanwar, nobody has started work on this yet but I have just now raised the priority of this & changed the status from ToDo to Planned.  Planned status means when team members finish their current assignments, this will be next in line.  We will update you along the way via this issue.

**Comment by rohan-kadkol** [comment] 2023-01-12 13:49
When trying to investigate this a bit more, I realized that even in the [`Table -> Virtualized story`](https://itwin.github.io/iTwinUI/react/?path=/story/overview--page), there is an abrupt jump.

[Video8.webm](https://user-images.githubusercontent.com/45748283/212081877-4927f725-421b-4f63-a44c-e992f9b1f6da.webm)

When trying to copy the sandbox example locally and then testing it, I got the same abrupt jumps as above. But the duration of the jumps was much longer with the comboboxes.

[Video9.webm](https://user-images.githubusercontent.com/45748283/212083504-a9fa4b41-f46c-4073-9c1b-dbd816ac5716.webm)

So the issue might not specifically be because of the ComboBox in a Table. It might be something virtualization specific.

**Comment by mayank99** [comment] 2023-01-12 17:22
the situation in that sandbox is kinda wild

https://user-images.githubusercontent.com/9084735/212136008-24415c46-625e-4cc6-a5bf-b3f5ef88fea4.mov

**Comment by veekeys** [comment] 2023-01-13 09:31
Few things have noticed:
- It is reproducible with single column which has `Combobox` with selected value. If you just remove `value`, no issues
- If you put anything else than `Combobox` (i.e. `Select`), it works fine
- If you change sandbox to use react version 18, the issue disappears too

**Comment by mayank99** [comment] 2023-01-13 14:38
@veekeys I was getting same behavior in react 18. Can you verify and link your sandbox if issue is no longer present?

**Comment by rohan-kadkol** [comment] 2023-01-13 14:39
What I have noticed, is that this infinite large row jumps bug happens from `itwinui-react 1.38.0` onwards. For example, in [this sandbox](https://codesandbox.io/s/react-typescript-forked-jxoy2u) with `v1.37.3`, the problem is not there. But upon changing `itwinui-react` to `1.38.0`, the problem is seen.

One of the PRs in [1.38.0](https://github.com/iTwin/iTwinUI-react/releases/tag/v1.38.0) is a combo box refactor PR (https://github.com/iTwin/iTwinUI-react/pull/623). So the issue might be with this PR.

> If you change sandbox to use react version 18, the issue disappears too

I too am getting the same error when changing the sandbox to react 18

**Comment by veekeys** [comment] 2023-01-13 14:52
> @veekeys I was getting same (buggy) behavior in react 18. Can you verify and link your sandbox if issue is no longer present?

https://codesandbox.io/s/react-typescript-forked-mq4yqj?file=/src/index.tsx

**Comment by mayank99** [comment] 2023-01-13 14:54
ah yeah, forgot to change to `createRoot.render` from `ReactDOM.render` 🤦 you're right, issue is not present when using `createRoot`

**Comment by mayank99** [comment] 2023-01-13 14:58
so then question to @vsnandanwar - anything blocking you from upgrading to react 18? we will attempt to fix this in react 17, but generally speaking, you will get the best experience using react 18.

**Comment by vsnandanwar** [comment] 2023-01-17 06:58
Hi @mayank99,

I have some packages which has restriction not to upgrade to react 18. so will you please try to fix this in react 17?

**Comment by vsnandanwar** [comment] 2023-01-23 06:49
Hi @mayank99 @FlyersPh9 @rohan-kadkol @adamhock ,

Will you please try this to fix in react 17 itself as there is an open issue of table virtualization for react 18?

**Comment by vsnandanwar** [comment] 2023-02-03 06:53
Hi @mayank99,

Will you please share me an update on this issue?

**Comment by mayank99** [comment] 2023-02-03 14:17
@vsnandanwar There is no update on this issue, but we have it in our "planned" items, which means we will get to it after we finish our currently assigned items.
![](https://user-images.githubusercontent.com/9084735/216625820-106c22c6-5ffc-433a-8e14-5c55aa0e5fbb.png)

**Comment by vsnandanwar** [comment] 2023-02-22 05:32
Hi @mayank99 , @rohan-kadkol, @FlyersPh9 ,

Will you please let me know if this is fixed or is in planned state still or is there any alternative wherein I will not get this abrupt jump while scrolling?

Thanks,
Vikram

**Comment by mayank99** [comment] 2023-02-22 14:19
Hey @vsnandanwar, it is still in planned state, and we ask you to please stop spamming this issue and tagging multiple people. It will not make this item move any faster.
There are many ways to avoid this abrupt jump:
- don't use virtualization (you can use pagination or try [`content-visibility`](https://web.dev/content-visibility/))
- don't use hundreds of comboboxes (it is bad UX, and table is meant for _displaying_ data)
- use react 18

You are also welcome to contribute to this issue by investigating the problem and submitting a pull request.

**Comment by FlyersPh9** [comment] 2023-04-06 18:18
Hi @vsnandanwar, we've been looking into this issue for a while and after some discussion and escalating the issue have decided to not address this in the current versions of iTwinUI.  We are starting to plan for [the next major versions of iTwinUI](https://github.com/iTwin/iTwinUI/milestones) which is planned to be available later this year.  In those next major versions the table will be refactored to use [TanStack Table v8](https://tanstack.com/table/v8) which may address this issue.

However, @adamhock is working on a CodeSandbox that will give you a slightly different solution to what you are trying to achieve.  I expect that to be shared before the end of this week.

**Comment by adamhock** [comment] 2023-04-06 18:37
Below is a CodeSandbox that has a workaround for what you are trying to achieve. Essentially, the `ComboBox` components are replaced with simple `Input` components. When an `Input` is focused, it changes to a `ComboBox` which you can use normally. Once the `ComboBox` is closed, it changes back into an `Input` component with the updated value. I've left some comments 
in `iTwinTable.tsx` highlighting the changes.

https://codesandbox.io/s/react-typescript-forked-ee64fn?file=/src/App.tsx

**Closed** 2023-04-06 18:37 UTC
Labels: bug, wontfix, has workaround, react
