### ISSUE TITLE
Popover automatically closes when focus is lost.

### ISSUE THREAD

**Issue by mathieu-fournier** [iTwin/iTwinUI#2284] opened 2024-10-04 16:18 UTC
### Describe the bug (current behavior)

Related to : [https://github.com/iTwin/appui/issues/1061](https://github.com/iTwin/appui/issues/1061)

When showing the Popup to change the Snap Mode, I move the mouse up to go select a Mode. But having the mouse in this little space (Red in the image below), closes the popup. Now that the popup is closed, I can no longer change the Snap Mode.  
This happens because, when the mouse is on top of the view, the Accudraw input field (Pink in the image) is automatically Focused. 
And focusing that input automatically closes the popup. 
Note : Auto-focusing the accudraw input is a design decision, we want to keep it that way.
![Image](https://github.com/user-attachments/assets/84626206-5e12-41b0-a738-3eb6a6e1453d)

What would be the best approach to fix this issue ?

Thanks (:

### Expected Behavior

I expect the popup to remain visible until I do an action that would make it close. 
Example : Pressing TAB to focus something else. Clicking on something else. Pressing Enter/Espace. Etc... 

### Link to minimal repro

example.com

### Package Version

- [ ] I'm using the latest version of iTwinUI.

### Anything else?

I'm using ITwinUI version [3.14.0](https://www.npmjs.com/package/@itwin/itwinui-react/v/3.14.0).

**Comment by mayank99** [comment] 2024-10-04 16:23
I think this is a duplicate of https://github.com/iTwin/iTwinUI/issues/2245? Please look at the workaround in there and let us know if that works for you.

**Comment by mayank99** [comment] 2024-10-08 16:18
This has been determined to be **working as intended** from iTwinUI's side. The root cause of this behavior is the repeated auto-focus of the Accudraw input field. During our discussions, we proposed alternatives that would avoid such issues altogether.

**Closed by mayank99** 2024-10-08 16:18 UTC
Labels: enhancement, react

**Comment by mathieu-fournier** [comment] 2025-03-26 18:38
@mayank99  
> During our discussions, we proposed alternatives that would avoid such issues altogether.
I've lost the discussion, do you recall what where the alternatives ?
