### ISSUE TITLE
Search box with tags

### ISSUE THREAD

**Issue by DineshBodewar** [iTwin/iTwinUI#782] opened 2022-10-17 06:16 UTC
Provide a component which includes a search box and tags below it.
So when user select a search value a tag will appear below the search box as example shown in below step 3

Step 1: Search box
![1  searchbox](https://user-images.githubusercontent.com/115967995/196092944-50e62651-efd2-4b7d-98d9-5c7df432421a.png)

Step 2: User search and select a search value
![image](https://user-images.githubusercontent.com/115967995/196098728-41760ec9-51a6-488b-83e6-bec0dc99b13c.png)

Step 3: Search box with tags for selected search values
![image](https://user-images.githubusercontent.com/115967995/196093772-124521c0-9590-4dfc-8c13-73d276103396.png)

**Comment by mayank99** [comment] 2022-10-17 14:34
Closing as duplicate of https://github.com/iTwin/iTwinUI-react/issues/650 which is currently being worked on.

**Closed by mayank99** 2022-10-17 14:34 UTC
Labels: enhancement

**Comment by FlyersPh9** [comment] 2022-10-17 15:15
@mayank99 is step #3 achievable with our current React components where the tags appear underneath the select component?

**Comment by FlyersPh9** [comment] 2022-10-17 15:28
@DineshBodewar [I've opened an issue here](https://github.com/iTwin/iTwinUI-react/issues/883) for displaying the selected items within a tag container underneath the combobox.
