### ISSUE TITLE
ExpandableBlock: Add disabled state in React

### ISSUE THREAD

**Issue by adamhock** [iTwin/iTwinUI#1263] opened 2023-05-09 15:41 UTC
#### Feature
There is already CSS written to achieve a disabled state for `ExpandableBlock`, but there is no way of achieving this state in React

#### Examples
![image](https://github.com/iTwin/iTwinUI/assets/78564221/590710a8-5555-48a8-bb6f-0cd4be7c2e9c)

**Comment by mayank99** [comment] 2023-05-09 15:44
Duplicate of #883

**Closed by mayank99** 2023-05-09 15:44 UTC
Labels: enhancement, good first issue
