### ISSUE TITLE
Tooltips not showing in Dropdown's submenu

### ISSUE THREAD

**Issue by IvanJK97** [iTwin/iTwinUI#1617] opened 2023-10-05 18:37 UTC
#### Describe the bug (actual behavior)

Tooltips in dropdown's submenu are not showing

#### Expected behavior

Should show tooltip when hovering over a submenu item

#### Reproduction
Link to a minimal repro: 
https://codesandbox.io/s/menu-item-with-tooltip-forked-z86p2h?file=/src/App.tsx
Observe that Item#4 tooltip does not show when hovered.

##### Steps to reproduce
1.  Create a dropdown menu with a menu item that has a submenu
1.  Create some menu items wrapped with tooltip in the submenu
1.  Hovering over those menu items does not show tooltip

#### Additional information

We recently upgraded from 2.11.6 to 2.12.10, which was when we started seeing this issue.

**Comment by mayank99** [comment] 2023-10-05 20:07
I think the root cause of this issue is the same as #1137, which was fixed in v3.

For v2, it might also get addressed together with #1616, so I'll close this for now.

**Closed by mayank99** 2023-10-05 20:07 UTC
Labels: bug
