### ISSUE TITLE
Tooltip: Misaligned tooltip inside LabeledInput IconButton

### ISSUE THREAD

**Issue by HaveSpacesuit** [iTwin/iTwinUI#938] opened 2022-12-28 16:33 UTC
It is possible to add an icon button in the LabeledInput component, but adding a tooltip to the button causes the button to be misaligned.

```tsx
<LabeledInput
  label="With tooltip"
  svgIcon={
    <Tooltip content="lock">
      <IconButton styleType="borderless">
        <SvgLock />
      </IconButton>
    </Tooltip>
  }
  iconDisplayStyle="inline"
/>
```

![image](https://user-images.githubusercontent.com/15036346/209843303-9292531e-dc6e-4ae5-ad5f-ff88510d966d.png)

Please see a reproducible example in this code sandbox.
https://codesandbox.io/s/itwinui-react-minimal-example-forked-pr3dkx?file=/src/App.tsx

**Comment by gretanausedaite** [comment] 2022-12-30 13:49
Hi!
Thanks for the issue!

We recommend to use refs with Tooltip in this case: https://codesandbox.io/s/itwinui-react-minimal-example-forked-28pths?file=/src/App.tsx

Our input with inline icon is adding iTwinUI classes to user provided svgIcon. In your case, the class was added to Tooltip (as top layer of svgIcon). Therefore the layout was wrong.

**Comment by mayank99** [comment] 2023-01-03 14:27
Closing this as it's working as intended (for now). In the future we can improve this by replacing `cloneElement` with a wrapping element.

**Closed by mayank99** 2023-01-03 14:27 UTC
Labels: bug, react
