### ISSUE TITLE
Review documentation content and demos

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#1035] opened 2023-01-27 21:12 UTC
- [ ] Alert
- [x] Avatar
- [x] Badge
- [x] Breadcrumbs
- [ ] Carousel
- [ ] Color picker
- [ ] ComboBox
- [ ] DatePicker
- [x] Dialog
- [ ] Dropdown menu
- [ ] Expandable block
- [ ] File upload
- [ ] Footer
- [ ] Header
- [ ] Information panel
- [ ] Non ideal state
- [ ] Progress indicator
- [ ] Side navigation
- [ ] Stepper
- [ ] Surface
- [ ] Table
- [ ] Tabs
- [ ] Tag
- [ ] Tile
- [ ] Toast
- [ ] Tooltip
- [ ] Tree
- [ ] Button
- [ ] Button group
- [ ] Checkbox
- [ ] Fieldset
- [ ] Input
- [ ] Input group
- [ ] Radio
- [ ] Radio Tile
- [ ] Select
- [ ] Slider
- [ ] Textarea
- [ ] Toggle Switch
- [ ] Anchor
- [ ] Blockquote
- [ ] Code
- [ ] Keyboard keys
- [ ] Typography

**Comment by mayank99** [comment] 2023-01-30 14:09
Duplicate of #961?

**Closed** 2023-01-30 14:19 UTC
Labels: documentation
