### ISSUE TITLE
Introduce an "uptime" check on deployed sites

### ISSUE THREAD

**Issue by FlyersPh9** [iTwin/iTwinUI#873] opened 2022-12-21 20:36 UTC
We accidentally deployed with a mistake which resulted in our site 404ing.  We should introduce a way to notify us of downtime.

**Comment by rohan-kadkol** [comment] 2022-12-21 20:45
Not sure what is the best way, but I found a tool called [Upptime](https://upptime.js.org) that automatically creates an issue on GitHub whenever an endpoint goes down. We can then add information of the downtime in the issue for users to be updated. The issue is automatically closed when the website/endpoint is back up again.

To prevent flagging expected downtimes like the 30 seconds of downtime when we deploy to GitHub pages, we can look into changing the scan interval. The default scan interval is every 5 minutes. But we can change this to every 12 hours or every 1 day.

**Comment by mayank99** [comment] 2023-05-02 18:37
I haven't seen any downtime in the last few months, and I doubt we're going to get to this task, so I'm closing this issue. Can always be reopened someday.

**Closed by mayank99** 2023-05-02 18:37 UTC
Labels: maintenance
