### ISSUE TITLE
Table Custom Filters - Unable to clear filter if no results found.

### ISSUE THREAD

**Issue by orlandoortegajr** [iTwin/iTwinUI#1473] opened 2023-08-04 19:07 UTC
#### Describe the bug (actual behavior)
We are using a table with custom filters for columns that match a specific field within a user's object. For example: a user can have roles "Account-Admin", "Bentley Employee", etc... Reason why we went with custom filters is so that you can filter these roles in any order/combination.

Issue we are running into is that when we filter for some kind of role and the role does not exist on the table, or maybe an incorrect value was entered, the table shows the empty content text, however, unlike the default table filters, the filter icon does not remain highlighted which means they have to refresh the page to see all the data as they cannot simply clear the filter.

#### Expected behavior
When setFilter method is called in the FilterButtonBar for a custom filter and there are no results in the table matching the filter, the filter icon should remain highlighted so that the user is able to clear the filter.

#### Reproduction
Link to a minimal repro: [Repro](https://codesandbox.io/s/lucid-khorana-strkhz?file=/src/App.tsx)

##### Steps to reproduce
1. Click on the filter in the role column.
2. Type a value that is not matched by any record in the table such as "Executive"
3. See that you cannot go back unless you refresh the page.

**Comment by orlandoortegajr** [comment] 2023-08-04 19:09
Also follow up question, in the example here: https://itwin.github.io/iTwinUI/react/?path=/story/core-table--custom-filter. It doesnt show the icon highlighted as well is there a way to make sure the table knows it has a column that is currently being filtered. Wasn't sure if this was a bug or a question but filed as bug just in case.

**Comment by mayank99** [comment] 2023-08-04 20:55
maybe a duplicate of #1204? @adamhock was looking into that issue, so i will wait for him to comment.

---



> in the example here: [itwin.github.io/iTwinUI/react/?path=/story/core-table--custom-filter](https://itwin.github.io/iTwinUI/react/?path=/story/core-table--custom-filter). It doesn't show the icon highlighted when you are filtering by one of the values.

yea, this sounds like a separate bug we'll need to investigate

**Comment by orlandoortegajr** [comment] 2023-08-10 12:43
@mayank99 @adamhock any updates?

**Comment by mayank99** [comment] 2023-08-10 12:51
@orlandoortegajr Adam is no longer working on iTwinUI, and we do not have the bandwidth to investigate this right now. So for quickest results, you should consider looking into this yourself. If not, we'll eventually get to it when we finish our higher-priority tasks.

**Comment by orlandoortegajr** [comment] 2023-08-10 20:11
@mayank99 okay sounds good, will talk to my manager about potentially working on it and submitting a PR, will be going on vacation next week so will probably be raising it sometime in the Aug 21 week.

Thanks for letting me know!

**Comment by rohan-kadkol** [comment] 2023-12-01 22:25
I believe this is not a bug as the Table is working as intended. In your codesandbox, you were filtering the data yourself. So when the filter matches none of the rows, you were passing no rows to the Table. Since the Table receives no rows, it does not show the filter icons since there are no rows to filter.

In order to always pass the correct data to the Table but only change the filter value independently, you can use the props that `Filter` gives.

[Updated Sandbox](https://codesandbox.io/p/sandbox/keen-tom-z468fx?file=%2Fsrc%2FApp.tsx%3A60%2C3-64%2C53)

```tsx
<Table
  // ...
  Filter: CustomFilter
/>
```

```diff
+ import { TableFilterProps } from "@itwin/itwinui-react";

- const CustomFilter = () => {
+ const CustomFilter = ({
+     column,
+     clearFilter,
+     setFilter,
+   }: TableFilterProps<Record<string, unknown>>) => {
    // ...
  };
```

**Closed by rohan-kadkol** 2023-12-01 22:25 UTC
Labels: bug

**Comment by mayank99** [comment] 2023-12-04 13:54
See related thread too: https://github.com/iTwin/iTwinUI/discussions/1672#discussioncomment-7535913
