### ISSUE TITLE
User Icon Status is not displayed correctly with svg web components

### ISSUE THREAD

**Issue by pranaykute06** [iTwin/iTwinUI#246] opened 2021-08-18 14:42 UTC
We have started using svg icon web components (**@itwin/itwinui-icons-elements**) in our ITwinUI Blazor.
We have noticing that user icon status is not displayed correctly.

Please see the highlighted markup

![image](https://user-images.githubusercontent.com/82197220/129918688-28b89c90-0b0c-4b31-8632-962f96b40967.png)

**Comment by mayank99** [comment] 2021-08-18 15:06
Thanks for the issue. This is a slight duplicate of #230, but we're working on it.

Did you find any other instances where this was a problem?

**Comment by pranaykute06** [comment] 2021-08-20 10:49
I have also noticed one more place where svg web component is displayed in correctly
Progress Radial Component
Please find screen shot for ref.
![image](https://user-images.githubusercontent.com/82197220/130222387-f8225684-0382-4455-ba36-fa6fc55c9b5d.png)

**Closed** 2021-08-30 18:11 UTC
Labels: bug
