### ISSUE TITLE
Circles in radio buttons and handles of toggles are offset

### ISSUE THREAD

**Issue by Vermanas** [iTwin/iTwinUI#406] opened 2021-12-07 21:36 UTC
We noticed that in one of the Design Review modal dialogs that is using iTwin UI, circles in radio buttons and handles of toggles are offset a bit and not aligned properly (notice unit system radio buttons and issues) toggle:

![image](https://user-images.githubusercontent.com/15130462/145109506-2aaa458d-69ef-416b-8200-ecfd24940422.png)

Seems like it is affected by the browser window size, as resizing it changes where circles/handles are being placed.

Easiest to reproduce in Firefox, but same thing happens in Chrome to a lesser extent.

**Comment by JoeZman** [comment] 2021-12-08 16:18
FYI... regarding the toggle button, I noticed the styling has height: 20px, but the actual size is 22px.  Guessing on the "iui-toggle" style **box-sizing: border-box** is missing?  Doesn't fix the problem, just noticed the issue.

![image](https://user-images.githubusercontent.com/17307464/145235942-ea96b545-cf24-4fe7-9f61-08c66def0010.png)

**Comment by FlyersPh9** [comment] 2021-12-10 22:31
Was investigating this today.  I am able to recreate the radio dots being off center when zooming in w/ the browser, but I am unable to recreate the dot shifting around when the radio is placed within a modal and the browser window is resizing.

I tried replacing the `<SVG>` dot in the radio button using `::after`.  The dot still appeared off center at 110% browser zoom.  I did notice at 110% zoom the devtools read the supposedly 16px circle as 15.99px.  To ensure it wasn't any of our global CSS causing issues, I recreated the component in Codepen & the issue is there as well.
![Screen Shot 2021-12-10 at 5 29 14 PM](https://user-images.githubusercontent.com/849817/145649434-66c0a843-6a5e-4c5f-909a-267467f97214.png)

I did make some changes to the actual SVG file being used in [this branch](https://github.com/iTwin/iTwinUI/tree/jon/fix-checkbox-radio-sizing), and I think it has helped shifting around the slightest bit or it's all in my head at this point.

**Comment by mayank99** [comment] 2022-01-11 15:57
@Vermanas @JoeZman We have made some changes to checkbox/radio spacing that have been released in iTwinUI-css 0.44.0 and iTwinUI-react 1.29.0. Please verify if it fixes the issue on your end; we might make similar changes in toggle-switch if it does.

**Comment by FlyersPh9** [comment] 2022-01-24 19:15
@Vermanas @JoeZman @anandgaikwad can you check if #426 / iTwinUI-css 0.44.0 and iTwinUI-react 1.29.0 fixes the checkbox / radio centering issues?  #455 is being reviewed currently and should introduce the fix for toggle switches in the near future.

**Comment by morganadrales** [comment] 2022-01-28 17:06
@FlyersPh9 We've updated to itwinui-react 1.29.3 and itwinui-css 0.44.1 and the previous issue with the inner dot of the radio button being off center seems to be fixed.

The issue now is that on smaller resolution screens (or if you zoom in on a standard monitor to, say, 110%), there is a secondary outline to the radio button that overlaps. 

Here is a screenshot:
![image](https://user-images.githubusercontent.com/85196633/151589940-33dfbc6b-5de9-469a-898c-aa6d575726ed.png)

Originally, the outline was thinner as well. In QA, it looks like this (compared to the above screenshot):
![image](https://user-images.githubusercontent.com/85196633/151590092-4cf59067-2e49-4b45-8180-33f401c5ca85.png)

Should I open a new bug for this?

**Comment by FlyersPh9** [comment] 2022-01-28 17:39
Thanks for sharing this @morganadrales.  This is for sure related to our attempted fix to the off center bug, so I don't think you need to file a new bug.

Previous we had a `<div>` with a 1px border & we nested the dot within that.  The 1px border is what we believe was causing the off centering issue.  So we tried to fix that by placing the border using `::after` and inherited the border from the `<div>`.  We'll look into this early next week.

**Comment by mayank99** [comment] 2022-01-31 11:31
>  there is a secondary outline to the radio button that overlaps.

@morganadrales This should not be happening. Could you double check your lockfile to make sure there are no conflicting versions of itwinui-css in there? It's possible that the second border is coming from an older version of itwinui-css (via transitive deps).

For more info, see https://github.com/iTwin/iTwinUI-react/wiki/Version-conflicts

**Comment by morganadrales** [comment] 2022-01-31 14:54
> @morganadrales This should not be happening. Could you double check your lockfile to make sure there are no conflicting versions of itwinui-css in there? It's possible that the second border is coming from an older version of itwinui-css (via transitive deps).

@mayank99 Yes, we have multiple versions of itwinui-css because of packages we pull in that do not have itwinui-css listed as a peerDep. Jason is discussing this with Jon and I think he is going to post something in the Team channel, as we do not want to import directly from a transitive dependency if it could be helped. Aside from that, I resolved our itwinui-css versions for testing purposes and the secondary outline is indeed gone, but now we see differing dot sizes inside the radio button:

![image](https://user-images.githubusercontent.com/85196633/151815800-0bcfbbfd-1bd1-4457-ba71-57fecf616040.png)
![image](https://user-images.githubusercontent.com/85196633/151815777-b588f029-0851-44c9-a192-23965098e13c.png)

**Comment by morganadrales** [comment] 2022-02-01 14:07
@mayank99 It appears to still be happening even if we resolve our itwinui-css versions in our yarn.lock file.
We're using 0.44.2:
![image](https://user-images.githubusercontent.com/85196633/151982953-65b98c99-63e2-47b6-8464-506542aa30de.png)

And I still see the double outline. It looks fine at 100%, but is off-center/overlaps when you zoom or are on a smaller resolution screen.
![image](https://user-images.githubusercontent.com/85196633/151983115-0d44752c-9656-4de4-b4f8-5bc198c489f6.png)

**Comment by FlyersPh9** [comment] 2022-02-01 14:50
@morganadrales is this deployed anywhere that I could use DevTools to inspect?

**Comment by morganadrales** [comment] 2022-02-01 15:49
@FlyersPh9 We haven't deployed the version where we've resolved the versions of itwinui-css, but the current deployed version is having the same UI issue with the radio buttons. The link is here
https://qa-review-uks.itwin.bentley.com/review/9533db14-2055-4ea3-b160-7726ec7f9aae?pw365Mode

You can open the settings modal where the above screenshots have come from by clicking the gear icon on the far right of the bottom status bar

https://user-images.githubusercontent.com/85196633/152001806-fb0ca950-d2f4-4731-9599-2c9f6c806b85.mp4

**Comment by morganadrales** [comment] 2022-02-02 18:05
update: I have verified that 0.44.1 of itwinui-css has fixed the radio button issue. The problem I was previously experiencing is that after adding a resolution to our package.json for itwinui-css ^0.44.1, lerna clean/bootstrap did not cascade that version to our civil packages that depend on an older version of itwinui-css. So those packages were still using 0.24.7 etc. and was applying a border to the iui-radio-dot on top of the :after border styling. That's what was causing the double outline issue. Clearing out the node_modules folder with rimraf and then re-bootstrapping fixes the issue 👍

**Comment by Vermanas** [comment] 2022-02-08 14:06
@FlyersPh9, @mayank99  we did some additional testing and noticed that in **Firefox** the radio button is still offset depending on screen/browser window size. See image below of how it looks when browser window is at 1349x704 (please ignore the double outline on radio button).

Chromium based browser don't have this problem anymore, at any screen size.

![image](https://user-images.githubusercontent.com/15130462/153002229-d72ec07c-f732-4773-bea7-0c6145a36177.png)

**Comment by FlyersPh9** [comment] 2022-02-11 16:08
@Vermanas I see in your screenshot that the radio buttons have the double border issue that Morgan explained [up above](https://github.com/iTwin/iTwinUI/issues/406#issuecomment-1028211807).  If you get the double border issue resolved, is it still having off center issues?

**Comment by FlyersPh9** [comment] 2022-02-16 19:56
@Vermanas @morganadrales @anandgaikwad @JoeZman can you confirm what your OS scaling is set to?  By any chance is it set to 125%?

**Comment by Vermanas** [comment] 2022-02-22 20:34
@FlyersPh9 With double border issue resolved, still see the problem in Firefox if browser window is resized. Scaling is set to 100% and I'm using 23" monitor. I can get similar results on 15.6 laptop screen when resizing as well. Here is a short video of the problem, notice the circle moving when browser window size is changed: 

https://user-images.githubusercontent.com/15130462/155214069-316a443f-bf7f-4fd4-802e-2e9e70461df9.mp4

**Closed** 2022-03-14 18:44 UTC
Labels: bug
