### ISSUE TITLE
Input icon is not visible when using iTwinUI v3 and v2

### ISSUE THREAD

**Issue by saskliutas** [iTwin/iTwinUI#1867] opened 2024-02-21 08:47 UTC
### Describe the bug (current behavior)

Icon is not visible in `InputWithDecorations` and `SearchBox` components from iTwinUI v3 if there are any components from iTwinUI v2 used also.

### Expected Behavior

Icon should be visible.

### Link to minimal repro

https://stackblitz.com/edit/vitejs-vite-g3dw9a?file=src%2FApp.tsx&terminal=dev

### Steps To Reproduce

1. Open sandbox
2. Icons are not visible in `SearchBox` and `InputWithDecorations` components.
3. Remove `TextV2` component and it's import. Icons become visible after sandbox is refreshed.

**Comment by rohan-kadkol** [comment] 2024-02-21 14:17
I think the issue is coming from the `svg` selector that is not scoped only to v2:

https://github.com/iTwin/iTwinUI/blob/f6dae8dfd50bdf5bf5c125e7920ba76b9d4124ab/packages/itwinui-css/src/utils/icon.scss#L21

**Comment by mayank99** [comment] 2024-02-21 15:27
🚀 Fixed in [2.12.24](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%402.12.24), thanks for reporting this! @saskliutas

**Closed by mayank99** 2024-02-21 15:27 UTC
Labels: bug
