### ISSUE TITLE
Table: improve typing for `columns`

### ISSUE THREAD

**Issue by mayank99** [iTwin/iTwinUI#886] opened 2022-11-15 15:32 UTC
https://github.com/iTwin/iTwinUI-react/pull/940 was a hacky workaround to fixing build errors for users, and it even resulted in our own vite playground failing when running `tsc`. Need to investigate this issue and have proper types (without `any`).

#1514:
- Build must pass even if user doesn't have a strong type for `columns`.
- The user must NOT be required to cast their columns using `as Column[]`.

Others:
- Table stories should remove `{...args}` because it hides TS errors. (#1543)

TODOs:
- There must be a proper test for more complicated permutations of the Table in a testing app (e.g. nextjs or vite, via playwright).
- ~~Vite playground build should ideally reintroduce `tsc`~~ (done) and pass (~~playground build currently does not run in CI~~ done).
  - Same with storybook ideally.

**Comment by rohan-kadkol** [comment] 2023-01-31 15:28
This issue has multiple parts:
1. Give a type error when a top-level header is passed (to reinforce that we don't support multi-level headers) (https://github.com/iTwin/iTwinUI/issues/886#issuecomment-1362950474). I worked mostly on this part.
2. The other parts are listed in the issue description and other comments.

---

I considered a couple of approaches for part `#1`:
* To cut-paste the code from `@types/react-table` to `itwinui-react` (`base-react-table.d.ts`) and remove dep on `@types/react-table`
    * Users' apps don't depend on `react-table`; but they download it since we depend on it. So if we don't depend on it, they won't download it. Thus, `Column` will not be available and they cannot typecast their columns to `Column[]`. Thus, we can only remove this dep when/if we don't need users to use types from `react-table`.
  * Also, if we depend on `@types/react-table`, then users also indirectly depend on it. So when they download the dependency, their version includes the `columns` in `ColumnGroupInterface` even though we exclude it in our version. So I'm not sure how to exclude something that has been declared in the base package. Or maybe I misunderstood how TS works.
* In `react-table-config.ts`, override `columns` to type of `undefined` or similar by overriding `ColumnGroupInterface` inside of `react-table-config.ts`
  * This didn't work since same-name variables should have the same type.
  * ![image](https://user-images.githubusercontent.com/45748283/215583892-c814d567-614d-475d-808a-b964a12e3aaa.png)
* Add `override.d.ts` file
  * This allows to add on to the types in `@types/react-table`. It doesn't allow to exclude declarations already mentioned in `@types/react-table`.
* Having a local dependency of `@types/react-table` on an edited folder version of the `@types/react-table` that excludes `columns` from `ColumnGroupInterface` (using `yarn add file:src/types/react-table`)
  * But local dependencies are not accessible by the users of itwinui-react. So they can't import `Column` to cast `columns as Column[]`
* There might be a way to export react-table types from itwinui-react, but didn't try that too much. So we export `Column`, `FieldType`, etc. directly, outside any namespace, similar to how we export component props using the barrel. (not sure if this require lots of changes to the index.d.ts type file).

As mentioned, I did not work too much on part `#2`. But here is one observation I made:
* Not passing `accessor` in all columns seemed to eliminate the need for casting `columns` to `Column[]`. I don't know how that worked before because I was not able to reproduce it now.

---

I am unassigning

**Comment by mayank99** [comment] 2023-07-21 13:55
reopening because:
- we will not be able to migrate to tanstack table in time for v3
- we can make breaking changes to types in v3, so we can duplicate react-table types into our package and fix any issues.
- there are issues with old columns format (#1428)

**Comment by mayank99** [comment] 2023-07-21 14:03
there is a new [`satisfies`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html) keyword in typescript 4.9 that might help us satisfy the column types.

e.g. we could change our types so that it works with `[] satisfies Columns`; users on older typescript versions can forcibly fallback to `[] as Columns`.

**Comment by rohan-kadkol** [comment] 2023-09-01 18:51
> * Table stories should remove `{...args}` because it hides TS errors.

@mayank99 To confirm, what kind of type errors could be hidden because of `{...args}`?

**Comment by mayank99** [comment] 2023-09-01 18:58
> what kind of type errors could be hidden because of `{...args}`?

spreading `{...args}` can hide any errors that may be caused by the props that come before (for example `columns` and `data`) because `args` is assumed to override it

**Comment by mayank99** [comment] 2023-09-12 21:03
i think this is fine to keep closed, even with the minor pending issues that may be addressed in future PRs.

**Comment by rohan-kadkol** [comment] 2023-09-12 21:10
> i think this is fine to keep closed, even with the minor pending issues that may be addressed in future PRs.

Sounds good, closing this issue for now with #1514. Will solve https://github.com/iTwin/iTwinUI/pull/1514#discussion_r1323515670 in another PR and reference this issue.

**Closed by rohan-kadkol** 2023-09-12 21:10 UTC
Labels: enhancement, react
