### ISSUE TITLE
ProgressRadial spinner has "Loading." text visible for short time

### ISSUE THREAD

**Issue by DovileVirbalaite** [iTwin/iTwinUI#1930] opened 2024-03-19 10:27 UTC
### Describe the bug (current behavior)

![image](https://github.com/iTwin/iTwinUI/assets/88542754/699a7a61-db07-471f-9174-494507f3a931)
When spinner appears it sometimes shows "Loading." text for a split second. This easily reproduces on mobile devices (even more visible on slower ones) and looks like a glitch.

https://github.com/iTwin/iTwinUI/assets/88542754/59410e07-abea-43ea-b03b-a170cb800935

### Expected Behavior

No "Loading." text when spinner is shown.

### Link to minimal repro

https://stackblitz.com/edit/github-ccf7j7?file=src%2FApp.tsx

### Steps To Reproduce

1. open minimal reproduction example on mobile device
2. refresh page to render spinner
3. "Loading." text is visible for a split second 
If device is slower it will reproduce almost every time, also reproduces with faster devices but less often.

### Anything else?

Seems like issue appeared after these changes https://github.com/iTwin/iTwinUI/pull/1859

**Comment by Ben-Pusey-Bentley** [comment] 2024-03-19 15:10
Thanks for submitting this issue. I have not been able to reproduce it myself, since I can't get it to happen on desktop and the stackblitz simply crashes for me when I try to test on mobile. Watching the attached video, it seems to me like the text is being used a placeholder while the device is unable to render the spinner. @mayank99  is this an intentional side effect of adding the visually hidden text? If not, then there must be some override we can add to make sure that this text is never visually rendered.

**Comment by DovileVirbalaite** [comment] 2024-03-19 16:10
Stackblitz example on device (it also sometimes crashes for me on device, refresh helps, but still wanted to include minimal example for you to reproduce):

https://github.com/iTwin/iTwinUI/assets/88542754/092dd7b1-e538-41b4-8e05-6aa2358a7f38

I can also very rarely reproduce it on browser.

While debugging on device I can see spinner is rendered first, then "Loading." text appears, so it doesn't look like it is used as a placeholder when unable to render the spinner.

**Comment by rohan-kadkol** [comment] 2024-03-19 16:21
I am able to reproduce this. Moving the `VisuallyHidden` outside of the `ShadowRoot` in [`ProgressRadial.tsx`](https://github.com/iTwin/iTwinUI/blob/3c5552fbb2ad779395c2f38d3fe30167b4a96d48/packages/itwinui-react/src/core/ProgressIndicators/ProgressRadial.tsx#L92-L95) fixes this issue.

<img width="597" alt="image" src="https://github.com/iTwin/iTwinUI/assets/45748283/b133c26b-9cae-4d12-826b-f833ac4f56e3">

Investigating it further.

**Comment by mayank99** [comment] 2024-03-21 17:20
Fixed in [3.7.1](https://github.com/iTwin/iTwinUI/releases/tag/%40itwin%2Fitwinui-react%403.7.1)

**Comment by mayank99** [comment] 2024-03-25 15:08
@DovileVirbalaite This has nothing to do with declarative shadow DOM, which is only used during server-side rendering. Are you sure this is only happening in older iOS versions? Can you look a bit more closely and share more information with us? 🙏

**Comment by mayank99** [comment] 2024-03-25 15:35
@DovileVirbalaite Again, this shouldn't be affected by declarative shadow DOM, because we fall back to using the widely supported `attachShadow` method on client. Are you even using server-side rendering? Is it reproducible in the stackblitz you shared earlier? Could you share a screen recording? Are you able to inspect the DOM state in devtools and share a screenshot?

**Comment by DovileVirbalaite** [comment] 2024-03-26 10:30
Sorry, I might be wrong, I don't have a lot of experience with shadow DOM.
Investigated a bit further, here are the screenshots of inspect:
Working correctly, no "Loading." text (iOS 16.4):
<img width="1659" alt="Screenshot 2024-03-26 at 11 29 50" src="https://github.com/iTwin/iTwinUI/assets/88542754/1c374dcc-0614-453a-8583-502cd8e077c9">
Not working, "Loading." text is shown (iOS 15.5):
<img width="1622" alt="Screenshot 2024-03-26 at 11 32 46" src="https://github.com/iTwin/iTwinUI/assets/88542754/9eb2b909-ec79-40ea-9c6f-56df62756afe">
Seems some css is missing comparing these two. Also did some debugging in ShadowRoot.tsx, and noticed on lower iOS versions `supportsAdoptedStylesheets` returns `false`, while on higher version it returns `true` and Loading text gets hidden. 
<img width="582" alt="Screenshot 2024-03-26 at 12 21 11" src="https://github.com/iTwin/iTwinUI/assets/88542754/f96e0914-ba2f-46f0-aa62-d94fe341ced6">

**Closed** 2024-03-26 19:33 UTC
Labels: bug
